---
title: "EB-proj"
author: "Junming Guan"
date: "2026-06-27"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---



::: {.hidden}
$$
    \newcommand{\E}{\mathbb{E}}
    \newcommand{\R}{\mathbb{R}}
    \newcommand{\P}{\mathbb{P}}
    \newcommand{\Rn}{\mathbb{R}^n}
    \DeclareMathOperator{\Var}{Var}
    \newcommand{\vbar}{\bar{v}}
    \newcommand{\EBproj}{\text{EB-proj}}
    \newcommand{\KL}[2]{\text{KL}\left(#1 \ \| \ #2\right)}
    \newcommand{\Unif}{\text{Unif}}
    \newcommand{\Rad}{\text{Rad}}
    \newcommand{\Eq}{\mathbb{E}_q}
    \newcommand{\Eqv}{\mathbb{E}_q[v]}
    \newcommand{\Eqvv}{\mathbb{E}_q\|v\|^2}
    \newcommand{\EqPv}{\mathbb{E}_q[v^\top P v]}
    \newcommand{\norm}[1]{\left\|#1\right\|}
    \DeclareMathOperator{\EBNM}{EBNM}
$$
:::

## Motivation

We have seen that the low-plus-noise assumed in flashier, when applied to centered and whitened data is generally not ideal. For example, if the data matrix is generated as

$$
Y=\ell f^\top + E, \quad E_{ij}\stackrel{\text{iid}}{\sim} N(0, \sigma^2),\quad  \ell_i \stackrel{\text{iid}}{\sim} \Rad,\quad f_j\stackrel{iid}{\sim} N(0, \sigma_f^2),
$$
then the whitened and centered data matrix has rather complex distribution for which the above model is misspecified and in general not compatible with the iid noise assumption. Furthermore, the prior after the whitening transformation could also change: for example, in the simple case where $y=\ell$ and $\ell_i\sim \Rad(p)$, centering and whitening changes the distribution to a normalized two point distribution such that shrinkage to a $\{\pm 1\}$ distribution seems unsatisfactory. A different and perhaps more principled route is to model the whitened data, or the projection matrix, directly.

## The model

Here we propose EB-proj, "**E**mpirical **B**ayes on **proj**ection", to model a given a rank-$K$ projection matrix $P$ in a probabilistic fashion and seek to extra latent directions from it. As an example, consider the case where the subspace spanned by the $P$ contains an "interesting" latent vector $v$, $P=vv^\top/\|v\|^2+V_0V_0^\top$, where $V$ is a random projection matrix onto the rank-$K-1$ subspace orthogonal to $v$. In this case, the alignment of $P$ with $v$, defined as

$$
\rho_v(P)=\frac{v^\top Pv}{\|v\|^2},
$$

is exactly $1$. Of course, it could also be the case that $P=\sum u_ku_k^\top$ and $v=\sum a_k u_k$. There are also situations where the alignment is not exact, in which case, $\rho_v(P)<1$. This could arise when one considers a low-rank whitening of a data matrix and some signals are removed in the process. This suggests that to probabilistically model $P$, we should also model the randomness in the alignment $\rho_v(P)$; this is analogous to assuming random Gaussian noise in the low-rank-plus-noise model. As is evident from the previous discussion, given a latent vector $v$ and an alignment index $\rho$, the choice of $P$ is not unique, leaving room for random modeling. We thus consider the probability measure on the ser of all rank-$K$ projection matrices, given $v$ and $\rho$: 

$$
p(P \mid v, \rho) = \frac{p(\rho \mid P, v) \,p(P \mid v)}{p(\rho \mid v)}.
$$
Given $P$ and $v$, $\rho$ is fixed, so $p(\rho \mid R, v)=\delta(\rho-\rho_{\text{obs}})$, where $\rho_{\text{obs}}=v^\top P v/\|v\|^2$. We assume that $P$ is uniformly drawn from the Haar measure on the Grassmannian maniford. Hence $p(P \mid v) \propto 1$ and 

$$
\rho \mid v \sim \operatorname{Beta}(k/2, (n-k)/2).
$$

Under this model, 

$$
p(P \mid v, \rho) \propto \delta(\rho-\rho_{\text{obs}}) \rho^{k/2-1}(1-\rho)^{(n-k)/2-1}.
$$
Introducing a prior $\pi(p)\sim \operatorname{Beta}(a,b)$, and letting $a=k/2$, we have

$$
p(P \mid v) = \int^1_0 p(P \mid v, \rho) \pi(d\rho) \propto (1-\rho_{\text{obs}})^{b-(n-k)/2}.
$$
We thus have the following "rank-1" data generating process:

$$
\begin{aligned}
  v & \sim g^{\otimes n} \\
  \rho \mid v & \sim \operatorname{Beta}(k/2, b) \\
  P \mid \rho, v & \sim \Unif\,(\{\mathcal{P}_{n,K}:\ \rho_{\text{obs}}=\rho\}).
\end{aligned}
$$


## Variational objective

The marginal log likelihood is given by

$$
 \log \int p(P\mid v) g(dv).
$$

Consider a variational approach, the exact ElBO is

$$
F_{\EBproj}(q, g) = \Eq\left[-\frac{n-k-2b}{2}\log(1-\rho_{\text{obs}})\right] - \KL{q}{g} +C,
$$

where $C=\log\Gamma\left(\frac{n-k}{2}\right)+\log\Gamma\left(\frac{k}{2}+b\right)-\log\Gamma\left(\frac{n}{2}\right)-\log\Gamma(b)$. The expectation is in general not in closed form. A easy-to-evaluate surrogate is

$$
\widehat{F}_{\EBproj}(q, g) = -\frac{n-k-2b}{2}\log\left(1-\frac{\Eqv^\top P \Eqv}{\Eqvv}\right) - \KL{q}{g} +C,
$$

and a more accurate one is

$$
\widetilde{F}_{\EBproj}(q, g) = -\frac{n-k-2b}{2}\log\left(1-\frac{\EqPv}{\Eqvv}\right) - \KL{q}{g} +C.
$$

The following result follows from Jensen's inequality.

::: {.lemma #lem:lower-bound-obj}
$$
\widehat{F}_{\EBproj}(q, g) \le \widetilde{F}_{\EBproj}(q, g) \le F_{\EBproj}(q, g).
$$

:::

As a special case which we will investigate firther, consider the Rademacher prior $g=\Rad(\tfrac12)$ on $v$. We write the surrogate EB-proj objective as

$$
\widehat{F}(\vbar)\equiv \widehat{F}_{\EBproj}(q, \Rad(\tfrac12)) = \frac{n-2k-b}{2}\log \left(1-\frac{\vbar^\top P\vbar}{n}\right)-\sum_{i=1}^n h(\vbar_i)+C,
$$
where $\vbar:=\Eqv$ and

$$
h(x)=\frac{1+x}{2}\log(1+x)+\frac{1-x}{2}\log(1-x).
$$ 


When analyzing a framework involving an optimization problem, there are two important questions:

1. Does optimizing the objective give what we want?
2. Does the algorithm optimize or approximately optimize the objective?

We first answer the question. In particular, if the observed projection matrix $P$ does not contain any signal, i.e., $P\sim \Unif(\mathcal{P}_{n, K})$, the uniform distribution on the set of all rank-$K$ $n$-by-$n$ projection matrices, is the null solution the optimum of the objective, at least locally?


The following results says that: under the null, the Rademacher EB-proj surrogate objective does not favor a solution that is far away from 0.


::: {.theorem #thm:global-null-stability}

Suppose $K$ and $b$ are fixed as $n\to\infty$, and $P\sim\Unif(\mathcal P_{n,K})$. For every fixed $\varepsilon>0$, there exists $a_\varepsilon>0$ such that

$$
\P_{P\sim\Unif(\mathcal P_{n,K})}\left[
\sup_{m\in[-1,1]^n, \ \ \|m\|_2\ge \varepsilon\sqrt n}
\widehat{F}(m)
\le
-a_\varepsilon n
\right]
\to 1.
$$

:::

However, this theorem does not rule out the near-zero (e.g., $o(\sqrt{n})$) solutions. In practice, we could either discard a solution with norm less than a prespecified threshold, as is done in flashier, or use the following result to reject it.


::: {.theorem #thm:null-calibration}

Suppose $P\sim \Unif(\mathcal{P}_{n, K})$ and $v\sim g^{\otimes n}$. Then

$$
\P_{P\sim\Unif(\mathcal{P}_{n, K})}\left[\sup_{q}\widehat{F}_{\EBproj}(q, g) \ge t\right] \le e^{-t}.
$$
:::



## An alternative formulation

We attempt to derive a similar framework from the spiked model assumed in flashier:

$$
Y \in \R^{n\times K}=v z^\top + E, \quad E_{ij}\stackrel{\text{iid}}{\sim} N(0, \sigma^2),\quad  v_i \stackrel{\text{iid}}{\sim} g,\quad z_j\stackrel{iid}{\sim} N(0, \sigma_z^2).
$$

Integrating out $z$, and denote $\kappa=\sigma_z^2/\sigma^2$, we have

$$
y_j\mid v \sim N\left(0,\Sigma_v\right),
\qquad \Sigma_v=\sigma^2 I_n+\sigma_z^2vv^\top =\sigma^2(I_n+\kappa vv^\top).
$$


Consider the projection $P=Y(Y^\top Y)^{-1}Y^\top$, the induced density of $P$ on the Grassmannian has the form

$$
\begin{aligned}
p(P\mid v,\kappa)& \propto
(1-\eta(v, \kappa))^{K/2}
(1-\eta(v, \kappa)\, \frac{v^\top P v}{\|v\|^2})^{-n/2} \\
&=(1+\kappa \norm{v}^2)^{-K/2}
(1-\frac{\kappa v^\top P v}{1+\kappa \norm{v}^2})^{-n/2},
\qquad \eta(v, \kappa)=\frac{\kappa \norm{v}^2}{1+\kappa \norm{v}^2}.
\end{aligned}
$$

Equivalently,

$$
\begin{aligned}
\log p(P\mid v,\kappa)
&=
C+\frac K2\log(1-\eta(v, \kappa))
-\frac n2\log(1-\eta(v, \kappa)\rho) \\
&= C+\frac{n-K}{2}\log(1+\kappa \norm{v}^2)
-\frac n2\log(1+\kappa \norm{v}^2-\kappa v^\top P v),
\qquad \rho=\frac{v^\top P v}{\|v\|^2}.
\end{aligned}
$$

The marginal log likelihood for a fixed $\kappa$ is given by

$$
\log \int p(P\mid v,\kappa) g(dv).
$$

Taking a variational approach gives the following variational objective:

$$
\widehat{F}_{\text{EB-spiked-proj}}(q,g,\kappa)
= \frac K2\log(1-\eta(v, \kappa))
-\frac n2\log(1-\eta(v, \kappa)\hat\rho(q))
-\KL{q}{g}+C,
$$

or

$$
\widehat{F}_{\text{EB-spiked-proj}}(q,g,\kappa)
= \frac{n-K}{2}\log(1+\kappa \Eqvv)
-\frac n2\log\left(1+\kappa (\Eqvv- \vbar^\top P \vbar)\right)
-\KL{q}{g}+C,
$$

Interestingly, when $\kappa\to\infty$, we have $\eta(v, \kappa)\to 1$ and the objective reduces to

$$
\widehat{F}_{\text{EB-spiked-proj}}(q,g,\infty)
= -\frac n2\log(1-\hat\rho(q))
-\KL{q}{g}+C,
$$

which is very similar to the Rademacher EB-proj objective. This suggests that the Rademacher EB-proj objective is a limiting case of the spiked model when the signal-to-noise ratio is large.

We can also see the connection by profiling over $\kappa$. Taking derivative and setting it to 0 gives

$$
\kappa = \frac{(n\hat{\rho}-K)_+}{K(1-\hat{\rho})\Eqvv}.
$$

Plugging this back into the objective gives

$$
\begin{aligned}
\widehat{F}^{\operatorname{prof}}_{\text{EB-spiked-proj}}(q,g)
&=
\begin{cases}
-\KL{q}{g}+C,
& \hat\rho(q)\le K/n,\\[6pt]
\frac{n-K}{2}\log\left(\frac{(n-K)\hat\rho(q)}
{K(1-\hat\rho(q))}\right)
-\frac n2\log\left(\frac{n\hat\rho(q)}{K}\right)
-\KL{q}{g}+C,
& \hat\rho(q)>K/n,
\end{cases} \\
&=\begin{cases}
-\KL{q}{g}+C,
& \hat\rho(q)\le K/n,\\[6pt]
-\frac{n-K}{2}\log(1-\hat\rho(q))
-\frac{K}{2}\log\hat\rho(q)
-\KL{q}{g}+C',
& \hat\rho(q)>K/n.
\end{cases}
\end{aligned}
$$


Consider the convex conjugate of log: $-\log x = \max_{\tau > 0} \{\log \tau - \tau x + 1\}$, we have

$$
\log(1-\eta(v, \kappa)\hat\rho(q)) = \max_{\tau>0} \{\log \tau - \tau(1-\eta(v, \kappa)\hat\rho(q)) + 1\}.
$$

So the surrogate objective can be written as

$$
\widehat{F}^\tau_{\text{EB-spiked-proj}}(q,g,\kappa)
= C_\tau + \frac K2\log(1-\eta(v, \kappa))
+\frac {\tau n}{2} \eta(v, \kappa)\hat\rho(q) - \KL{q}{g},
$$

which looks like the flashier objective with Normal prior on $z$, profiled over $z$ (eq. 54-55 in EBMF_cov_ideas):

$$
\widehat{F}^z_{\text{flashier}} = \frac{\alpha n\hat{\rho}(q)}{2\sigma^2} + \frac{K}{2}\log(1-\alpha) - \KL{q}{g} + C'',
$$

where $\alpha = \eta(v,\kappa)= \frac{\kappa \Eqvv}{1+\kappa \Eqvv}$. So for fixed $\kappa$ (hence fixed $\alpha$ and $\eta(\vbar, \kappa)\equiv \eta(\vbar)$), the update for $q$ is given by (Table 1 in EBMF_cov_ideas):

$$
\EBNM\left(\frac{nP \vbar}{\eta(\vbar)n\hat{\rho}(q)+K \sigma^2_{eff}}, \frac{\sigma^2_{eff} \Eqvv}{\eta(\vbar)(\eta(\vbar)n\hat{\rho}(q)+K \sigma^2_{eff})}\right),
$$

where

$$
\sigma^2_{eff} = \frac{1}{\tau}.
$$

The update for $\kappa$ is given by

$$
\hat\kappa_{\tau}=
\frac{(n\tau\hat\rho-K)_+}{K\Eqvv}.
$$

Hence, the update for $\alpha=\eta$ is given by

$$
\hat\eta_\tau=\left(
1-\frac{K}{N\tau\hat\rho}
\right)_+,
$$

which matches the MLE update for $\alpha$ in Table 1 in EBMF_cov_ideas.

The update for $\tau$ is given by

$$
\hat\tau
=\frac{1}{1-\hat\eta\hat\rho(q)}.
$$


## Analyses

- [Initial exploration of EB-proj, with shifted Rademacher](shifted_rademacher_for_EB-proj.html)
  - TODO: It seems we need to choose the correct rank. Investigate this.
