---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
bibliography: references.bib
---

This repo contains misc explorations.

# ICA vs flashier

We want to compare fastICA's rank-1 update with that of flashier. Matthew previously examined an [example](https://stephens999.github.io/misc/fastica_02.html) where rank-1 fastICA almost perfectly picks up one column of the true mixing matrix, but flashier does not. Our conjecture is that flashier's failure arises from an overemphasis on the *fit* term. We plan to investigate this further and potentially improve flashier's rank-1 update.

## fastICA as a Bayesian ICA with Rademacher prior on the sources

rank-1 FastICA can be considered as an EM algorithm with a Rademacher prior on the sources, with a spectral shift step to accelerate convergence [@DSS]. Therefore, it is also equivalent to rank-1 EBCD with Rademacher prior. Consider the model for $Y\in \mathbb{R}^{n\times d}$

$$
Y_{ij} \sim \mathcal{N}(a_i s_j, \sigma^2), \quad s_i \sim \text{Rad}(1/2),\quad \sum_{i}^n a_i^2=1.
$$

fastICA estimates $\mathbf{s}=\begin{bmatrix}s_1 & \dots s_d\end{bmatrix}^\top$ by first estimating the "inverse" of $\mathbf{a}$, via the following steps:

-   Pick an initial $\mathbf{w}$

-   Iterate

    -   $\mathbf{s}=Y^\top \mathbf{w}$

    -   Denoising: $\mathbf{s}^+=f(\mathbf{s})$

    -   $\mathbf{w}^+=Y \mathbf{s}^+$

    -   $\mathbf{w}=\mathbf{w}^+ / \|\mathbf{w}^+\|$.

The first two steps are the E-step that constructs the estimated posterior mean $\mathbb{E}[\mathbf{s} \mid Y, \mathbf{w}]$, and the last two steps are the M-step that maximize $\mathbb{E}_q[\log p(\mathbf{s}, Y \mid \mathbf{w})]$.

### Analyses

-   [Initial exploration of EB ICA](eb_ica.html)
-   [Exploration of flashier with Rademacher prior](ica_vs_flashier_rad_r1.html)

### Some observations

-   It seems that in the unbalanced binary ($\pm 1$) groups case, As the number of groups increaes, it becomes more likely for a rank-1 EB ICA fit or flashier with Rademacher prior fit with a random initialization to converge to a same solution.

-   Fitting a parallel ank-\$K_0\$ EB ICA model ($K_0 > 1$) is more likely to recover some of the true sources. However, a deflation scheme does not seem to work well, probably because of the initial poor rank-1 fit.

## Rank-1 flashier with stand-in matrix

Wwe posit this following model for an observed data matrix $\boldsymbol{Y}\in \mathbb{R}^{n\times d}$:

$$
\begin{aligned}
\boldsymbol{Y} &= \boldsymbol{M}+ \boldsymbol{\ell f}^\top + \boldsymbol{E} \\
\ell_{i}&\stackrel{iid}{\sim} g_\ell \\
f_{j}&\stackrel{iid}{\sim} g_f \\
E_{ij}&\stackrel{iid}{\sim} \mathcal{N}(0, \sigma^2),
\end{aligned}
$$

where $\boldsymbol{M}\in\mathbb{R}^{n\times d}$. We hope that $\boldsymbol{M}$ can act as a 'stand-in' matrix—if one chooses to fit a rank-1 model even if the true signals are of rank\>1, $\boldsymbol{M}$ will capture any remaining true signals without leaking any to the error term.

### Objective

1.  Find a small example in which fastICA works but PCA does not.

2.  In real data, does initializing flashier from fastICA produce better ELBO? Try it on some single cell data set. We should process the dataset in a way (e.g., log+1 transform) such that we can apply fastICA (which doesn't handle non-negative constraints)

3.  We conjecture that another possible reason why rank-1 flashier fails is the EB component. Try fixing the prior to the true data generating distribution.

4.  Try the following update:

    -   Update $\boldsymbol{\ell}$ and $\boldsymbol{f}$ by running flashier back fit on $\boldsymbol{Y}-\boldsymbol{M}$.

    -   Update $\boldsymbol{M}$ by truncated SVD on $\boldsymbol{Y} - \boldsymbol{\ell f}^\top$.

### Anlayses

-   [Analysis 1](ica_vs_flash_r1_update_1.html)

    -   exploration of 1, 3 and 4.

# References

::: {#refs}
:::
